// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAAzldC3_a1p980hSYikB-_vpRhyD3eLQ',
    appId: '1:806070159000:android:47df6c9a210c12c5c0b2ed',
    messagingSenderId: '806070159000',
    projectId: 'attendance-app-55b40',
    storageBucket: 'attendance-app-55b40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6URuYGVhHS3uJh8Yle-eJjUzwbnyPb7w',
    appId: '1:806070159000:ios:e67c5e03b95c95e6c0b2ed',
    messagingSenderId: '806070159000',
    projectId: 'attendance-app-55b40',
    storageBucket: 'attendance-app-55b40.appspot.com',
    androidClientId: '806070159000-msq6jtdbjk8h90cksefpfbg7c8sgfti7.apps.googleusercontent.com',
    iosClientId: '806070159000-ok5ntf9oc01r8p6kfkta4mfrrjrgru2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.employee',
  );
}
